### ISSUE TITLE
NPE in setAuthTheme for Digits button

### ISSUE THREAD

**Issue by Palgrover** [crashlytics/digits-android#51] opened 2016-01-27 20:00 UTC
Caused by: java.lang.NullPointerException
                                                                          at com.digits.sdk.android.DigitsAuthButton.setAuthTheme(DigitsAuthButton.java:93)
                                                                          at com.littlebox.mobile.fragments.OnboardingWelcomeScreenFragment.onCreateView(OnboardingWelcomeScreenFragment.java:68)
                                                                          at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                          at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                          at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                                          at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
                                                                          at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                                          at android.app.Activity.performStart(Activity.java:5259)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2174)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by efrohnhoefer** [comment] 2016-01-27 20:55
Is `Fabric.with(new Digits())` called before the button is setup?

**Comment by Palgrover** [comment] 2016-01-28 05:48
Yes

**Comment by Palgrover** [comment] 2016-01-28 06:09
Tried setting up button before that is also not working

**Comment by Palgrover** [comment] 2016-01-28 11:25
TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);
        View view = inflater.inflate(R.layout.fragment_onboarding_welcome_screen, container, false);
        DigitsAuthButton digitsButton = (DigitsAuthButton) view.findViewById(R.id.signUp);
        Fabric.with(getActivity(), new Crashlytics(), new TwitterCore(authConfig), new Digits());
        digitsButton.setAuthTheme(R.style.digitsButton);
        // Inflate the layout for this fragment

        digitsButton.setText("Get Started");
        digitsButton.setBackgroundResource(R.drawable.full_banner_button);
        digitsButton.setCallback(new AuthCallback() {
            @Override
            public void success(final DigitsSession session, String phoneNumber) {
                mListener.onMobileRegistered(session, phoneNumber == null);
            }

            @Override
            public void failure(DigitsException exception) {
                Log.d("Digits", "Sign in with Digits failure", exception);
            }
        });

**Comment by Palgrover** [comment] 2016-01-28 11:26
`TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);
        View view = inflater.inflate(R.layout.fragment_onboarding_welcome_screen, container, false);
        DigitsAuthButton digitsButton = (DigitsAuthButton) view.findViewById(R.id.signUp);
        Fabric.with(getActivity(), new Crashlytics(), new TwitterCore(authConfig), new Digits());
        digitsButton.setAuthTheme(R.style.digitsButton);
        // Inflate the layout for this fragment

        digitsButton.setText("Get Started");
        digitsButton.setBackgroundResource(R.drawable.full_banner_button);
        digitsButton.setCallback(new AuthCallback() {
            @Override
            public void success(final DigitsSession session, String phoneNumber) {
                mListener.onMobileRegistered(session, phoneNumber == null);
            }

            @Override
            public void failure(DigitsException exception) {
                Log.d("Digits", "Sign in with Digits failure", exception);
            }
        });`

**Comment by Palgrover** [comment] 2016-01-28 11:26
this is my code which was working earlier

**Comment by efrohnhoefer** [comment] 2016-02-10 18:53
Can you include the contents of `digitsButton `?

**Comment by martin1yness** [comment] 2016-03-08 07:52
I have a similar issue:

<pre>
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.digits.sdk.android.Digits.setTheme(int)' on a null object reference
     at com.digits.sdk.android.DigitsAuthButton.setAuthTheme(DigitsAuthButton.java:92)
</pre>

Sequence of Events:

1. Initialize Fabric.with(...) in the Application.onCreate
2. Load LoginActivity with Digits Button
3. Login with Digits
4. Logout of Application, load LoginActivity
5. Attempt to apply Theme to button again, Null Pointer thrown.

It seems the `Digits.getInstance()` is returning a null to the `setTheme()` method.

**Comment by martin1yness** [comment] 2016-03-09 01:44
Issue may have been due to one of the following:

- Android Emulator was in bad state
- Calling `Fabric.with(..)` multiple times overwrites the previous modules

**Comment by lpfmailtest** [comment] 2017-05-10 11:55
I had the same exception. There was an issue with Digits configuration. We need to add Digits and TwitterCode inside Fabric.with() method.

I am using below lines to use multiple fabric kit in app.

```
TwitterAuthConfig authConfig = new TwitterAuthConfig(getString(R.string.twitter_key), getString(R.string.twitter_secret));
Fabric.with(new Fabric.Builder(this).debuggable(true).kits(new Crashlytics(), new TwitterCore(authConfig), new Digits.Builder().build()).build());
```

**Comment by mikebonnell** [comment] 2017-07-26 00:09
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)

**Closed by mikebonnell** 2017-07-26 00:09 UTC
Labels: help wanted
